### ISSUE TITLE
stack depth limit test

### ISSUE THREAD

**Issue by ethers** [pipermerriam/ethereum-alarm-clock#54]
Looked at some code and tests and did some searches...
Didn't see / couldn't find the code and test, or where your own lib https://github.com/pipermerriam/ethereum-stack-depth-lib is used by the alarm clock

**Comment by pipermerriam** [comment]
It's incoming in the next release.  Check out https://github.com/pipermerriam/ethereum-alarm-clock/pull/55

**Comment by ethers** [comment]
:+1:
