### ISSUE TITLE
10 blocks in the future

### ISSUE THREAD

**Issue by jambtt** [pipermerriam/ethereum-alarm-clock#56]
Is there anyway around this? 

I was thinking of implementing alarm clock for my dice gambling game Etheroll.com to wait for 2-3 blocks before calling a function. Unfortunately, in the world of gambling, 10 blocks ~3mins is too long to wait for an outcome. Could you please PM me.

I would like to talk to you about some options, if possible.

Thanks.

**Comment by pipermerriam** [comment]
You can come chat with me in the gitter chat channel for alarm.

https://gitter.im/pipermerriam/ethereum-alarm-clock

**Comment by jambtt** [comment]
Ha! Found this issue from a long time ago, closed it just now. Thanks again.
