### ISSUE TITLE
Can't start when using Populus 1.6.8 (fix known)

### ISSUE THREAD

**Issue by veox** [pipermerriam/ethereum-alarm-clock#73]
`config.py` has

``` python
from populus.utils.wait import (
    Wait,
)
```

That fails in Python REPL:

``` python
>>> from populus.utils.wait import ( Wait, )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Wait'
```

There has probably been some change in a (recent) release, still investigating. [Release notes](https://populus.readthedocs.io/en/latest/release.html) don't mention any, it seems. :/

For ref, the `wait` API has been added in PR pipermerriam/populus#173 (Sep 6, 2016), which means it's been part of Populus [since v1.0.0](https://github.com/pipermerriam/populus/releases?after=v1.2.2).

EAC's `setup.py` specifies `"populus>=1.2.1"` as dep.

**Comment by veox** [comment]
If using `populus==1.2.2`, there seems to have been an incompatible API change in `web3`, a dependency of `populus`:

``` python
>>> from populus.utils.wait import ( Wait, )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/veox/.local/lib/python3.5/site-packages/populus/__init__.py", line 3, in <module>
    from .project import Project
  File "/home/veox/.local/lib/python3.5/site-packages/populus/project.py", line 4, in <module>
    from web3.utils.string import (
ImportError: No module named 'web3.utils.string'
```

So "pinning" to an earlier version of `populus` in EAC wouldn't work. Seems easier to update for incompatibility in OP.

**Comment by veox** [comment]
Looks like `populus.wait` is the correct module name now, not `populus.utils.wait` - [has been moved](https://github.com/pipermerriam/populus/commit/1d27206a0d57bcbd1244baa6ed777997222211d2#diff-a7d3d0994798119d800e5aa051880a6c).

**Comment by pipermerriam** [comment]
These are fun to catch up with, sorry I've not had the time to dive in and help at the PR level.  Working through these now.
