### ISSUE TITLE
Tests fail due to web3.py API changes (and eth-testrpc, too)

### ISSUE THREAD

**Issue by veox** [pipermerriam/ethereum-alarm-clock#77]
Working on addressing current Travis build fails, in repo/branch [veox/fix-travis-failing](https://github.com/veox/ethereum-alarm-clock/commits/fix-travis-failing).

6d01d2a98502b12e65a65d8a84de83e70db2bfb1 outlines reason for current meta-failure of the build system:

> `solc` has many dynamic library dependencies that are installed from package repositories, but are not cached by Travis between builds. The `solc` sources and built binary are cached, though.
>
> Current custom installation script for `solc` skips installing the dependencies, which results in broken builds.

That branch "solves" the issue by having Travis cache the dependency installation script, too, and calling it in every build. (A better approach might have been building a static `solc` binary, or actually taking a deeper look at how Populus does it.)

Regardless, fixing that allows the build to continue, and for [tests to fail](https://travis-ci.org/veox/ethereum-alarm-clock/builds/223623567#L2654) with:

``` python
  File "/home/travis/build/veox/ethereum-alarm-clock/tests/conftest.py", line 10, in <module>
    from web3.utils.encoding import (
ImportError: cannot import name 'decode_hex'
```

I guess the API of `web3.py` has changed.

**Comment by veox** [comment]
`web3.py` uses `ethereum-utils` since version 3.6.2. The latter has `decode_hex`, used [like this](https://github.com/pipermerriam/web3.py/search?utf8=%E2%9C%93&q=decode_hex&type=).

My installation has `ethereum-utils` 0.2.0, probably via `populus` dependency, which has `ethereum-utils>=0.2.0`in `install_requires` (see it [`setup.py`](https://github.com/pipermerriam/populus/blob/8fc7646feb5e538712e7a845008fb49ec841598e/setup.py#L29).

**Comment by veox** [comment]
There's more API drift when trying to run tests - `eth-testrpc` now includes `ehtereum-tester-client` functionality. Fixed in a1c1e9cb5780fd86dc3b33077450c68dbeeea422, in branch [veox/update-tests](https://github.com/veox/ethereum-alarm-clock/commits/update-tests).

I'm still managing to keep fixes for various failures in separate branches, and octopus-merging them into [veox/octopus-everything](https://github.com/veox/ethereum-alarm-clock/commits/octopus-everything).

Tests fail now [due to `solc` v0.3.6 being too old](https://travis-ci.org/veox/ethereum-alarm-clock/jobs/223930787#L2523), but I think I've seen an update-to-solc-v0.4 branch somewhere...

**Comment by pipermerriam** [comment]
I think the worst part of all of this is going to be that you'll almost definitely have to update solc to something `>0.4.0,<=0.4.8` and this is going to cause a bunch of failures in the contracts themselves.  This is a part I should be able to take on personally at some point here soon in the event that you get to that stage.

It is *possible* that `0.3.x` still ends up working with populus but I'm skeptical.

**Comment by veox** [comment]
A fix for this issue has been submitted to branch `piper/update-to-solidity-0.4.x`. (An auto-close message was not provided in relevant commit.)
